### ISSUE TITLE
should use 🍺 (beer mug) emoji

### ISSUE THREAD

**Issue by Strandinator** [lpil/mug#1]
it's in the title
(http://unicode.org/Public/emoji/1.0/emoji-data.txt)
was thinking 🍻 at first. but it's not called mugs, is it?
/s

**Comment by lpil** [comment]
I really want a coffee mug emoji!

![image](https://github.com/lpil/mug/assets/6134406/e03cd407-c65f-498a-bda6-fcb31e3f5857)
