### ISSUE TITLE
Add ability to receive a given number of bytes

### ISSUE THREAD

**Issue by massivefermion** [lpil/mug#2]
I know it makes sense to just pass 0 to `gen_tcp:recv` so that it reads all that is available, but in practice that does not happen.
I had this problem with `mungo`. Apparently when as the size of the packet grows, the network layer may need some time to get the response you expect, so you won't actually get what you want.
This is how I solved it in mungo, because each packet has its size in the beginning:

```gleam
pub fn receive(socket) {
  case tcp_receive(socket, 4) {
    Ok(<<size:32-little>>) ->
      case tcp_receive(socket, size - 4) {
        Ok(rest) ->
          bit_string.append(<<size:32-little>>, rest)
          |> Ok
        Error(Nil) -> Error(Nil)
      }
    Error(Nil) -> Error(Nil)
  }
}


@external(erlang, "gen_tcp", "recv")
fn tcp_receive(socket: Socket, length: Int) -> Result(BitString, Nil)
```

I prefer to use mug instead of having my own tcp functions, but I can only do it if this feature is provided.

Thanks

**Comment by lpil** [comment]
Thanks for the suggestion!

What is it that your program does when there is not enough data in the socket? The receive function will return a timeout in this case. If it is called again recursively it could end up busy looping, which seems bad for system performance? If the socket is switched into active mode I believe there is no way to limit the message size to a certain number of bytes, you get whatever it sends you.

**Comment by massivefermion** [comment]
That's actually a very good point, looks like my only choice is to use an active socket.
But it seems like mug does not provide that either. Will that be available?

**Comment by lpil** [comment]
It does, using [this function](https://hexdocs.pm/mug/mug.html#receive_next_packet_as_message). The active-once mode is generally recommended over full active mode as it can't flood the process mailbox with packets.
