### ISSUE TITLE
Add option to receive specific number of bytes

### ISSUE THREAD

**Issue by Hackder** [lpil/mug#5]
Add a function perhaps called `receive_exact(socket, size, timeout)`

I was toying around with the postgres protocol, and it is very common that two messages come back from the server in a quick succession, causing one `mug.receive` to contain one and a half or multiple messages. Because of this, I need to pass the connection through all functions where I use it:
```gleam
pub fn main() {
    let conn = todo
    let assert #(conn, Ok(data)) = receive_server_packet(conn)
    let assert #(conn, Ok(data2)) = receive_server_packet(conn)
}
```

In binary protocols, it is generally simple to receive only one packet, by receiving the header and then only the exact number of payload bytes. This would let me just use the connection, without the need to shadow the variable after every receive.

Similar issue was open before, but the problem got resolved in a different way #2 

I can draft a PR for this if you'd like

**Comment by lpil** [comment]
Could you show what code would look with and without this addition please 🙏 Thank you

**Comment by Hackder** [comment]
Of course. For clarity, this is not the complete implementation, but it is planty to illustrate the problem.

```gleam
import gleam/bit_array
import gleam/io
import mug

type Conn {
  Conn(socket: mug.Socket, buffer: BitArray)
}

fn current_receive(conn: Conn) -> #(Conn, BitArray) {
  let assert Ok(packet) = mug.receive(conn.socket, timeout_milliseconds: 1000)

  // Here we parse the server message acording to the protocol.
  // The packet might be the whole message, or it might contian only a part of the message (so we must recurse).
  // -----------------------------------
  // Or it might contain multiple messages (the second one may be partial). <- this is the important part
  // Therefor we either must receive all messages, until exhausted and return a list (which is impractical),
  // or return a new connection, which contains the extra data.
  // -----------------------------------

  case bit_array.concat([conn.buffer, packet]) {
    <<data:bytes-size(64), rest:bits>> -> #(Conn(conn.socket, rest), data)
    _ -> panic
  }
}

fn receive_exact(socket: mug.Socket, size: Int) {
  todo
}

const header_size = 5

fn with_exact_receive(conn: Conn) -> BitArray {
  let assert Ok(header) = receive_exact(conn.socket, header_size)
  let assert <<size:32>> = header

  let payload_size = size - header_size
  let assert Ok(data) = receive_exact(conn.socket, size - header_size + 1)
  let assert <<message:bytes-size(payload_size), 0>> = data

  // Notice that there is no need for recursion here, as we know the exact size of the
  // message. And no need for the buffer, because we never receive more data than we need.

  message
}

pub fn main() {
  let assert Ok(socket) =
    mug.new("localhost", port: 5432)
    |> mug.timeout(milliseconds: 1000)
    |> mug.connect()

  let conn = Conn(socket, buffer: <<>>)

  // Notice how the connection needs to be passed in and out of each function.
  // If someone forgets to do it, it will lead to a bug, which might be transiant,
  // depending on where it happens.
  let #(conn, packet) = current_receive(conn)
  let #(conn, packet) = current_receive(conn)
  let #(conn, packet) = current_receive(conn)
  let #(conn, packet) = current_receive(conn)

  // Notice how much simple it is here. No need to pass the connection around.
  let packet = with_exact_receive(conn)
  let packet = with_exact_receive(conn)
  let packet = with_exact_receive(conn)
  let packet = with_exact_receive(conn)

  io.debug(packet)
}

```

**Comment by lpil** [comment]
It would still need to take a timeout as that much data may never arrive. Would that impact it?

**Comment by Hackder** [comment]
There are two cases for the timeout:
- messages which fit into a single packet are no problem (works by default)
- messages that don't fit, could keep track of the timeout in the internal recursive loop.

The main issue is that the `Conn` must be passed into every function **and a new instance returned and stored by the developer** to maintain consistency. Because if the packet received contained more than one message, there is no way to put the extra bytes back into the socket. So, I would need to store them somewhere.

In the run of the mill, mutable language, you can just keep an internal mutable property within the Conn object. But here that's not possible. So I need to return a new instance, and make sure the next read from the socket uses that instance.

I suppose something like "linear types" could solve this on a language level, but gleam doesn't have them, and I don't really think they are a good fit for it.

In the end, I think this would make my life (and perhaps of many others) much easier, and less error prone. As this is a new function being added, it isn't a breaking change. And it is implemented in erlang (and already ffi-ed in mug). I ran into this while using this library: https://hex.pm/packages/postgresql_protocol
It suffers from the same problem. You need to pass the connection in and out of every function (and pray you don't forget once)

If I were to forget to do this once, let's say in the query logic, It may trigger only in rare cases where the size of the message is really specific and the next one is already ready... which would make this bug extremely hard to track down.

Btw. if you look at the sources of PGO they also do it by reading the exact number of bytes needed. (Notice how in PGO you don't need to pass thing in and out of every function)

**Comment by lpil** [comment]
Sorry, I'm not sure what is being proposed exactly now.

Is the function still useful to you given a timeout is required? And what might the implementation look like?

**Comment by Hackder** [comment]
Oh, yeah sorry, I should have been more clear.
I am looking for this function:
```gleam
pub fn receive_exact(
  socket: Socket,
  size: Int,
  timeout_milliseconds timeout: Int,
) -> Result(BitArray, Error) {
  gen_tcp_receive(socket, size, timeout_milliseconds: timeout)
}
```

Currently in mug, there is only `receive(socket: Socket, timeout: Int)` which passes `0` as the size to the underlying erlang function. I only want the erlang function exposed fully, with the size parameter as well.

This is the currently present function:
```gleam
pub fn receive(
  socket: Socket,
  timeout_milliseconds timeout: Int,
) -> Result(BitArray, Error) {
  gen_tcp_receive(socket, 0, timeout_milliseconds: timeout)
}
```

**Comment by lpil** [comment]
Fab! Let's add that function!

**Comment by Hackder** [comment]
Awesome, I added a PR for it!
